version: "3"

services:
  app:
    image: ghcr.io/macgurk/morphnet.homebudget:latest
    links:
      - db
    restart: unless-stopped
    volumes:
      - ./database:/app/database
    environment:
      - Auth__Issuer=homebudget-dev.morphnet.ch
      - Auth__Audience=homebudget-dev.morphnet.ch
      - Auth__Secret=#{AUTH_SECRET}#
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homebudget-dev.entrypoints=http
      - traefik.http.routers.homebudget-dev.rule=Host(`homebudget-dev.morphnet.ch`)
      - traefik.http.middlewares.homebudget-dev-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.homebudget-dev.middlewares=homebudget-dev-https-redirect
      - traefik.http.routers.homebudget-dev-secure.entrypoints=https
      - traefik.http.routers.homebudget-dev-secure.rule=Host(`homebudget-dev.morphnet.ch`)
      - traefik.http.routers.homebudget-dev-secure.tls=true
      - traefik.http.routers.homebudget-dev-secure.tls.certresolver=http
      - traefik.http.routers.homebudget-dev-secure.service=homebudget-dev
      - traefik.http.services.homebudget-dev.loadbalancer.server.port=80
      - traefik.http.services.homebudget-dev.loadbalancer.passHostHeader=true
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
