services:
  app:
    image: ghcr.io/macgurk/morphnet.homebudget:#{PROD_VERSION}#
    volumes:
      - ./database:/app/database
    restart: unless-stopped
    environment:
      - Auth__Issuer=homebudget.morphnet.ch
      - Auth__Audience=homebudget.morphnet.ch
      - Auth__Secret=#{AUTH_SECRET}#
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homebudget.entrypoints=http
      - traefik.http.routers.homebudget.rule=Host(`homebudget.morphnet.ch`)
      - traefik.http.middlewares.homebudget-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.homebudget.middlewares=homebudget-https-redirect
      - traefik.http.routers.homebudget-secure.entrypoints=https
      - traefik.http.routers.homebudget-secure.rule=Host(`homebudget.morphnet.ch`)
      - traefik.http.routers.homebudget-secure.tls=true
      - traefik.http.routers.homebudget-secure.tls.certresolver=http
      - traefik.http.routers.homebudget-secure.service=homebudget
      - traefik.http.services.homebudget.loadbalancer.server.port=8080
      - traefik.http.services.homebudget.loadbalancer.passHostHeader=true
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
