version: "3"

services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homebudget
      - MYSQL_USER=homebudget_admin
      - MYSQL_PASSWORD=#{MYSQL_PASSWORD}#
      - MYSQL_ROOT_PASSWORD=#{MYSQL_ROOT_PASSWORD}#
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    image: ghcr.io/macgurk/morphnet.homebudget:#{PROD_VERSION}#
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: unless-stopped
    environment:
      - Mysql__ConnectionString=server=db;database=homebudget;user=homebudget_admin;password=#{MYSQL_PASSWORD}#;
      - Auth__Issuer=homebudget.morphnet.ch
      - Auth__Audience=homebudget.morphnet.ch
      - Auth__Secret=#{AUTH_SECRET}#
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homebudget.entrypoints=http
      - traefik.http.routers.homebudget.rule=Host(`homebudget.morphnet.ch`)
      - traefik.http.middlewares.homebudget-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.homebudget.middlewares=homebudget-https-redirect
      - traefik.http.routers.homebudget-secure.entrypoints=https
      - traefik.http.routers.homebudget-secure.rule=Host(`homebudget.morphnet.ch`)
      - traefik.http.routers.homebudget-secure.tls=true
      - traefik.http.routers.homebudget-secure.tls.certresolver=http
      - traefik.http.routers.homebudget-secure.service=homebudget
      - traefik.http.services.homebudget.loadbalancer.server.port=80
      - traefik.http.services.homebudget.loadbalancer.passHostHeader=true
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
