name: Deploy development environment

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create and publish Docker image]
    types:
      - completed

jobs:
  deploy-dev-morphnet:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Wireguard
        run: |
          sudo apt install wireguard
          echo "${{ secrets.WIREGUARD_PRIVATEKEY }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 10.0.0.2 peer 10.0.0.1
          sudo wg set wg0 listen-port 48123 private-key privatekey peer ${{ secrets.WIREGUARD_ENDPOINT_PUBLICKEY }} allowed-ips 0.0.0.0/0 endpoint ${{ secrets.WIREGUARD_ENDPOINT }}
          sudo ip link set up dev wg0

      - name: Replace token
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./deploy/docker-compose/development/docker-compose.yaml"]'
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Upload something
        uses: moonpathbg/scp_uploader@latest
        with:
          host: 10.0.0.1
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./deploy/docker-compose/development/docker-compose.yaml"
          target: "/srv/docker-compose/homebudget-dev/"

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.SSH_USERNAME }}@10.0.0.1
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            cd /srv/docker-compose/homebudget-dev
            docker compose pull
            docker compose up -d
