name: Create and publish Docker image

on:
  release:
    types: [published]

jobs:

  build-and-publish-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkut repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Metadata action
      uses: docker/metadata-action@v5.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
